version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: module_5/docs/src/conf.py

python:
  install:
    - requirements: module_5/requirements.txt
    - method: pip
      path: module_5